apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-nginx
  labels:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.nginxService.externalPort }}
      targetPort: {{ .Values.nginxService.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
    component: worker
  type: {{ .Values.nginxService.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-phpfpm
  labels:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.phpfpmService.port }}
      targetPort: {{ .Values.phpfpmService.port }}
      protocol: TCP
      name: php
  selector:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
    component: worker
  type: {{ .Values.phpfpmService.type }}
